# -*- coding: utf-8 -*-
"""Data_Cleaning & Simple Data Analist-Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16S30KEs-OIEboaqDCfvp-ZZvTftYEHDk

# Data Cleaning in Python

Project: Airbnb Open Data – Data Cleaning and Preparation

Data Cleaning Steps:
1. Remove redundant and irrelevant columns
2. Standardize and rename column names
3. Identify and remove duplicate records
4. Clean and standardize individual column values
5. Handle missing values
6. Apply additional data transformations as needed

Dataset Source:
https://www.kaggle.com/datasets/arianazmoudeh/airbnbopendata
"

# Insert Dataset
"""

import pandas as pd

# Meng Import dataset-csv
data = pd.read_csv("Airbnb_Open_Data.csv")

# Mengecek 5 data teratas
data.head(5)

# Menampilkan keseluruhan kolom
data.columns

# Menampilkan dimensi data
data.shape

# untuk mengecek informasi data
# membandingkan nilai yg tidak null terhadap yang null pada tiap kolom
data.info()

"""# a. Remove redundant and irrelevant columns"""

data.info()
# lihat pada bagian last_review (perbedaan datanya sangat besar dibandign sebelumnya)
# namun pada kasus ini kita drop dari review_per_month

data.columns

columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review']
columns_to_drop = ['reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license','id']

# Menghitung jumlah kolom
len(columns_to_keep)

# Menghitung jumlah kolom
len(columns_to_drop)

"""1. Filtering Data (First Method) - (Buat variabel tiap kali mau edit dataset)"""

# menampilkan data sesuai variabel kolom
# tampilan hanya menampilkan query terakhir
data[columns_to_keep]
data[columns_to_drop]

dk = data[columns_to_keep]
dd = data[columns_to_drop]

# drop kolom
data_DC1 = data.drop(columns = ['license']) # cara ke-1
data_DC = data.drop(columns = dd) # drop dari variabel data_DC
data_DC.head(2) # total jadi 19 kolom
data_DC.shape # cek dimensi

"""2. Dropping Column (Second Method)- (Tanpa buat variabel tiap kali mau edit dataset)"""

data.head(1) # kolum di data masih full
data.columns

data.drop(columns = dd,inplace = True) # drop langsung ke data aslinya, tanpa buat variabel baru
data # data asli yg udah di drop

# Note: kl udah di drop gak bisa di drop lagi (Error)

"""# b. Standardize and rename column names"""

# dalam merename column, menggunakan dictionary
data.columns

# merename kolom NAME
data.rename(columns = {"NAME":"Name"})
data.rename(columns = {"NAME":"Name"}, inplace = True) # mengubah data utama
data.head(2) # sudah keubah

for i in data.columns:
  print(i.upper()) # buat semua kolom kapital

for i in data.columns:
  print(i.lower ()) # buat semua lower

New_CN_L = [] # untuk menampung list kolom baru (Kecil)
for i in data.columns:
 New_CN_L.append(i.lower ()) # buat semua lower

New_CN_L # menampilkan semua kolom lower

data_cl = data.copy() # copy dari data utama, untuk coba ganti kolom ke lower

data_cl.columns = New_CN_L # ubah kolom yg awalnya H.bsar jadi kecil

data_cl.head(2) # nama kolom udah kecil semua

"""# c. Identify and remove duplicate records"""

data.duplicated() # kl duplicate True
data.duplicated().sum() # menghitung jumlah Duplicate True
data.duplicated().value_counts() # menghitung jumlah Duplicate True dan False

# clean_data = data.drop_duplicates() # buat variabel
# atau
# aku pilh yg bawah
data.drop_duplicates(inplace = True) # langsung ganti ke data utama

data.duplicated().value_counts() # udah gak ada data duplicate

"""# d. Clean and standardize individual column values"""

data.isna().sum() # last review merupakan kolom dengan NA terbanyak

data.drop(columns = "last review" )

# data_no_NA = data bersih tanpa NA
data_no_NA = data.dropna()

# ngecek lagi
data_no_NA.isna().sum() # udah gak ada data yang NA

"""# e. Handle missing values from the dataset

1. Mengubah host_identity_verified jadi UPPER
"""

# dari sini pake variabel data_no_NA
data_no_NA['host_identity_verified']

# Mengubah hasil host_identity_verified jadi uppercase
data_no_NA['host_identity_verified'].str.upper()

data_no_NA.head(2) # belum berubah

# cara mengubah hasilnya di data_no_NA
data_no_NA['host_identity_verified'] = data_no_NA['host_identity_verified'].str.upper()

data_no_NA.head(2) # udah berubah hasil di 'host_identity_verified'

"""2. Mengubah instant_bookable jadi bolean (0 atau 1)"""

data_no_NA ['instant_bookable'].apply(lambda x: 1 if x == True else 0)

data_no_NA.head(2)

data_no_NA ['instant_bookable'] = data_no_NA ['instant_bookable'].apply(lambda x: 1 if x == True else 0) # df(kolom) = df(kolom).method()

data_no_NA.head(5) # udah keubah (Done)

"""# f. Check for some more transformation

**1. Cek index atau penomerannya udah bener belum**
"""

data_no_NA['instant_bookable'][5] # ada nilainya satu

data_no_NA['instant_bookable'][15] # ini error gak ada nilainya, alasan nomer data lompat2

# cek data
data_no_NA.head(5) # nomor data lompat2

#solusi reset index
data_no_NA.reset_index(inplace = True)

# cek lagi
data_no_NA.head(5) # index yang benar udah muncul

# Terakhir coba lagi yg data no 15
data_no_NA['instant_bookable'][15] # udah gak error

"""**2. Ganti mata uang yg awalnya string jadi int dan menghilangkan spaci berlebih**

a. Data Cleaning
"""

data_no_NA.head(3) # pada price masih ada $, spasi berlebih, sama koma

type (data_no_NA['price'][2]) # data type masih string

data_no_NA.info() # dtype object- belum tentu string, bisa jadi campuran int, string, float, dll (cek lagi)

data_no_NA['price'].head(10) # buat cek jenis datanya dari perhitungan di bawah 🤑🤑
# 1. Dolar udah ilang

# 1. menghilangkan dolar
from numpy._core.defchararray import replace
data_no_NA ['price'] = data_no_NA['price'].str.replace('$','')

# 2. menghilangkang koma
data_no_NA ['price'] = data_no_NA['price'].str.replace(',','')

# 2. menghilangkang koma
data_no_NA ['price'] = data_no_NA['price'].str.replace(',','')

# 3. menghilangkang spasi gak jelas
data_no_NA ['price'] = data_no_NA['price'].str.replace(' ','')

"""b. Ganti mata uang menjadi string"""

# mengganti data type
data_no_NA['price'] = data_no_NA['price'].astype(int)

# mengecek kembali
type (data_no_NA['price'][100])
type (data_no_NA['price'][5]) # udah bener integer

"""# Ekspor file yang udah di Cleaning

"""

# ekspor data dari dataframe ke CSV
data_no_NA.to_csv('Cleaned_Data.csv')

data_no_NA.to_excel('Cleaned_Data.xlsx', index=False)

"""# Simple Data Analysis

1. Identified listing concentration across neighbourhood groups.
"""

neigh_count = data_no_NA['neighbourhood group'].value_counts()

plt.figure()
neigh_count.plot(kind='bar', label='Number of Listings')
plt.title('Number of Listings by Neighbourhood Group')
plt.xlabel('Neighbourhood Group')
plt.ylabel('Number of Listings')
plt.legend()
plt.show()

"""Distribusi listing di setiap neighbourhood group menunjukkan bahwa pasokan Airbnb tidak tersebar secara merata. Beberapa area memiliki jumlah listing yang jauh lebih tinggi dibandingkan area lainnya, yang mengindikasikan tingkat persaingan pasar dan konsentrasi permintaan yang lebih besar di wilayah tersebut.

2. Apakah minimum nights berpengaruh ke harga
"""

plt.figure()
plt.scatter(
    data_no_NA['minimum nights'],
    data_no_NA['price'],
    label='Listings',
    alpha=0.5
)
plt.title('Price vs Minimum Nights')
plt.xlabel('Minimum Nights')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

"""Hasil visualisasi menunjukkan tidak terdapat hubungan linear yang kuat antara jumlah minimum malam menginap (minimum nights) dan harga listing. Listing dengan harga tinggi dapat ditemukan pada berbagai ketentuan minimum menginap, yang mengindikasikan bahwa penetapan harga tidak terutama dipengaruhi oleh minimum nights, melainkan oleh faktor lain seperti lokasi, tipe kamar, dan fasilitas.

3. Price Distribution by Neighbourhood Group
"""

import matplotlib.pyplot as plt

plt.figure()
data_no_NA.boxplot(
    column='price',
    by='neighbourhood group',
    rot=45
)
plt.title('Price Distribution by Neighbourhood Group')
plt.suptitle('')
plt.xlabel('Neighbourhood Group')
plt.ylabel('Price (USD)')
plt.show()

"""Distribusi harga bervariasi antar neighbourhood group, di mana beberapa area menunjukkan harga median yang lebih tinggi serta rentang harga yang lebih luas. Hal ini mencerminkan adanya perbedaan tingkat permintaan pasar dan karakteristik listing di setiap wilayah.

4. Number of Reviews vs Price
"""

plt.figure()
plt.scatter(
    data_no_NA['number of reviews'],
    data_no_NA['price'],
    alpha=0.5,
    label='Listings'
)
plt.title('Price vs Number of Reviews')
plt.xlabel('Number of Reviews')
plt.ylabel('Price (USD)')
plt.legend()
plt.show()

"""Visualisasi menunjukkan tidak adanya korelasi yang kuat antara harga listing dan jumlah ulasan (number of reviews). Hal ini menunjukkan bahwa harga yang lebih tinggi tidak selalu berbanding lurus dengan volume pemesanan, sehingga popularitas listing kemungkinan dipengaruhi oleh faktor lain selain harga.

#
"""